version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "deep-risk-model"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-XXXXXXXXXXXX"
s3_prefix = "deep-risk-model"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = ["DeepRiskModelFunction=XXXXXXXXXXXX.dkr.ecr.us-east-1.amazonaws.com/deep-risk-model"] 