AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Deep Risk Model API with Lambda

Globals:
  Function:
    Timeout: 30
    MemorySize: 1024
    Runtime: provided.al2
    Architectures:
      - x86_64
    Environment:
      Variables:
        RUST_LOG: info
        RUST_BACKTRACE: 1

Resources:
  DeepRiskModelFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      ImageConfig:
        Command: ["bootstrap"]
      Policies:
        - AWSLambdaBasicExecutionRole
        - Statement:
            - Effect: Allow
              Action:
                - s3:GetObject
                - s3:PutObject
              Resource: !Sub "arn:aws:s3:::${ModelBucket}/*"
      Events:
        GenerateFactors:
          Type: Api
          Properties:
            Path: /factors
            Method: post
            RequestParameters:
              method.request.header.Content-Type: true
        EstimateCovariance:
          Type: Api
          Properties:
            Path: /covariance
            Method: post
            RequestParameters:
              method.request.header.Content-Type: true
        HealthCheck:
          Type: Api
          Properties:
            Path: /health
            Method: get
      Tags:
        Project: DeepRiskModel
        Environment: Production

  ModelBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "${AWS::StackName}-model-data"
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      VersioningConfiguration:
        Status: Enabled
      LifecycleConfiguration:
        Rules:
          - Id: DeleteOldVersions
            Status: Enabled
            NoncurrentVersionExpirationInDays: 30

Outputs:
  ApiEndpoint:
    Description: API Gateway endpoint URL
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
  ModelBucketName:
    Description: S3 bucket for model data
    Value: !Ref ModelBucket 